### ISSUE TITLE
How to solve this? ValueError: invalid signal error

### ISSUE THREAD

**Issue by lengelberts** [kevinconway/daemons#23]
I am trying to work with SimulaQron (https://github.com/SoftwareQuTech/SimulaQron) on my Windows. However, when I want to start it (via "simulaqron start") I run into the error "ValueError: invalid signal error". The error seems to result from daemons: 
![image](https://user-images.githubusercontent.com/44855852/55154578-73e57b80-5155-11e9-9c17-3d0b79d3079a.png)

Therefore, I tried the example on https://github.com/kevinconway/daemons and this indeed gave the same error: 
![image](https://user-images.githubusercontent.com/44855852/55155952-f6bc0580-5158-11e9-8a67-348ca3127f4e.png)
Here foo2.py is the second .py file as indicated in the example, so the one with "`if __name__`".

It seems to me that the problem is with pidfile. The value for pidfile in `d = SleepyDaemon(pidfile=pidfile)` is in my case: 
`C:\Users\Lynn\Documents\Capstone\testdaemon sleepy.pid`
(Here, testdaemon is the directory in which the files of the example are stored.) 

I am wondering if someone has an idea what is causing this problem. It would be great to fix this so that I (and others) could work with SimulaQron and daemons via Windows.

**Comment by kevinconway** [comment]
@lengelberts I believe the issue is that the system, by default, is setting signal handlers for signals that are not supported in Windows. Here are the signals for which we register handlers:
```python
kill_signals = (
        2,  # SIGINT
        3,  # SIGQUIT
        6,  # SIGABRT
        15,  # SIGTERM
)
```
but Windows does not support SIGQUIT (https://docs.python.org/2/library/signal.html#signal.signal).

One possible way to start would be to make a subclass of the signal handler that uses a different set of signals even if that is the same set minus SIGQUIT. I'm not sure what other changes would need to happen for Windows support as I originally made this library with the intent on managing daemons in a unix/linux type of environment.

**Comment by lengelberts** [comment]
Thank you @kevinconway for your quick reply! This seems to be a reasonable explanation indeed. In that case I will for now just avoid using Windows.

**Comment by AckslD** [comment]
@kevinconway It might be nice to say in the setup.py that this package is only for MacOS and Unix. You can do this by for example adding
```
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: Unix",
        "Operating System :: MacOS"
    ],
```
as an argument to `setuptools.setup`.
